apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman-unused 
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: pacman-unused
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: pacman-unused
    spec:
      containers:
        - image: quay.io/jduimovich0/pacman-unused
          imagePullPolicy: Always
          name: container-image
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 10m
              memory: 50Mi